name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Environment
      run: export $(cat .env | xargs) && echo $VERSION && echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag crack-elasticsearch --build-arg VERSION="${VERSION}"
    - name: Run Crack
      run: docker run -t --rm -v $(pwd)/output:/crack/output crack-elasticsearch && ls -lah output/x-pack-core-"${VERSION}".crack.jar

